FROM golang:alpine AS build
ADD . /go/src/app
WORKDIR /go/src/app
# RUN go env -w GO111MODULE=on && go env -w GOPROXY=https://mirrors.aliyun.com/goproxy/,direct
RUN go build

FROM alpine:latest
LABEL org.opencontainers.image.authors="master@southfox.me"

COPY --from=build /go/src/app/org-roam-woven /usr/bin/org-roam-woven
EXPOSE 18080
USER 65534
CMD ["/usr/bin/org-roam-woven"]
