name: Emacs Docker Build

on:
  push:
    branches: [main]
    paths:
      - 'packaging/Dockerfile.emacs'
      - 'packaging/init.el'
      - '.github/workflows/emacs.yaml'
  pull_request:
    paths:
      - 'packaging/Dockerfile.emacs'
      - 'packaging/init.el'
      - '.github/workflows/emacs.yaml'
  workflow_dispatch:
    inputs:
      use_cn_mirror:
        description: "Use Chinese mirror sources"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  emacs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for emacs
        id: meta-emacs
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/emacs
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push emacs Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./packaging
          file: ./packaging/Dockerfile.emacs
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-emacs.outputs.tags }}
          labels: ${{ steps.meta-emacs.outputs.labels }}
          build-args: |
            CN_MIRROR=${{ github.event.inputs.use_cn_mirror || 'false' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Success notification
        if: success() && github.event_name != 'pull_request'
        run: |
          echo "🎉 Successfully built and pushed Emacs Docker image!"
          echo ""
          echo "📦 Available image:"
          echo "- ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/emacs:latest"
